# docker buildx bake --set "*.platform=linux/amd64" --load && docker-compose push
version: '3.7'
services:
  fakeservices.datajoint.io:
    build: .
    image: datajoint/nginx:v0.2.2
    ports:
      - "443:443"
